### PR TITLE
Validate the document ID before using it in a query

### PR DESCRIPTION
**Pull request by raboof**
This is likely not strictly necessary, but good to err on the safe side.

### CODE REVIEW

**Comment by iamamoose** [comment]
did this change come about because of an issue?

**Comment by raboof** [comment]
No - there was a CodeQL warning that we were using user-submitted input in a query, and while I would be highly surprised if this led to trouble, it seemed like good practice to validate it anyway.

**Comment by raboof** [comment]
Makes sense, https://github.com/Vulnogram/Vulnogram/pull/125

**Review by manhbacgiang678-dev — COMMENTED** [review]
VIET CAPITAL SECURITIES JOINT STOCK COMPANY 
0731000790235

**Pull request closed without merging**
